package com.nendo.argosy.ui.screens.common

import android.content.Context
import com.nendo.argosy.DualScreenManager
import com.nendo.argosy.data.emulator.EmulatorResolver
import com.nendo.argosy.data.emulator.PlaySessionTracker
import com.nendo.argosy.data.local.dao.GameDao
import com.nendo.argosy.data.preferences.SessionStateStore
import com.nendo.argosy.data.preferences.UserPreferencesRepository
import com.nendo.argosy.util.DisplayAffinityHelper
import io.mockk.mockk
import kotlinx.coroutines.CoroutineScope

internal fun launchTestDualScreenManager(
    scope: CoroutineScope,
    displayAffinityHelper: DisplayAffinityHelper,
    sessionStateStore: SessionStateStore,
    gameDao: GameDao,
    context: Context = mockk(relaxed = true),
    preferencesRepository: UserPreferencesRepository = mockk(relaxed = true),
    playSessionTracker: PlaySessionTracker = mockk(relaxed = true),
    emulatorResolver: EmulatorResolver = mockk(relaxed = true)
): DualScreenManager = DualScreenManager(
    context = context,
    scope = scope,
    gameDao = gameDao,
    gameRepository = mockk(relaxed = true),
    activeSaveRepository = mockk(relaxed = true),
    prefetchGameSaveDataUseCase = mockk(relaxed = true),
    platformRepository = mockk(relaxed = true),
    collectionRepository = mockk(relaxed = true),
    socialRepository = mockk(relaxed = true),
    downloadQueueDao = mockk(relaxed = true),
    downloadQueueRepository = mockk(relaxed = true),
    gameFileDao = mockk(relaxed = true),
    downloadManager = mockk(relaxed = true),
    gameActionsDelegate = mockk(relaxed = true),
    platformSyncQueue = mockk(relaxed = true),
    gameLaunchDelegate = mockk(relaxed = true),
    saveCacheManager = mockk(relaxed = true),
    getUnifiedSavesUseCase = mockk(relaxed = true),
    getUnifiedStatesUseCase = mockk(relaxed = true),
    stateCacheManager = mockk(relaxed = true),
    restoreCachedSaveUseCase = mockk(relaxed = true),
    activateSaveChannelUseCase = mockk(relaxed = true),
    restoreSaveChannelPointUseCase = mockk(relaxed = true),
    createSaveChannelUseCase = mockk(relaxed = true),
    copySaveChannelUseCase = mockk(relaxed = true),
    renameSaveChannelUseCase = mockk(relaxed = true),
    deleteSaveChannelUseCase = mockk(relaxed = true),
    restoreStateUseCase = mockk(relaxed = true),
    emulatorResolver = emulatorResolver,
    coreVersionExtractor = mockk(relaxed = true),
    fetchAchievementsUseCase = mockk(relaxed = true),
    raRepository = mockk(relaxed = true),
    raTileContentRepository = mockk(relaxed = true),
    achievementUpdateBus = mockk(relaxed = true),
    displayAffinityHelper = displayAffinityHelper,
    sessionStateStore = sessionStateStore,
    preferencesRepository = preferencesRepository,
    imageCacheManager = mockk(relaxed = true),
    romMRepository = mockk(relaxed = true),
    gameDocumentLoader = mockk(relaxed = true),
    documentHighlightStore = mockk(relaxed = true),
    resolveGameEmulatorContext = mockk(relaxed = true),
    hapticManager = mockk(relaxed = true),
    soundManager = mockk(relaxed = true),
    syncPreferencesRepository = mockk(relaxed = true),
    homeTileRepository = mockk(relaxed = true),
    homeTilePromptQueue = mockk(relaxed = true),
    appsRepository = mockk(relaxed = true),
    appShortcutActions = mockk(relaxed = true),
    notificationManager = mockk(relaxed = true),
    titleIdDownloadObserver = mockk(relaxed = true),
    homeGridPageRepository = mockk(relaxed = true),
    pageChooserEntrySource = mockk(relaxed = true),
    ambientAudioManager = mockk(relaxed = true),
    emulatorConfigDao = mockk(relaxed = true),
    configureEmulatorUseCase = mockk(relaxed = true),
    builtinCoreResolver = mockk(relaxed = true),
    saveHandlerRegistry = mockk(relaxed = true),
    steamDownloadQueueDao = mockk(relaxed = true),
    steamRepository = mockk(relaxed = true),
    playSessionTracker = playSessionTracker,
    permissionHelper = mockk(relaxed = true),
    steamContentManager = mockk(relaxed = true),
    repairImageCacheUseCase = mockk(relaxed = true),
    downloadFileStatusRepository = mockk(relaxed = true),
    gradientExtractionDelegate = mockk(relaxed = true),
    filePickerFlow = mockk(relaxed = true),
    gameThemeAudioCoordinator = mockk(relaxed = true),
    getPinnedCollectionsUseCase = mockk(relaxed = true),
    getGamesForPinnedCollectionUseCase = mockk(relaxed = true),
    advanceCollectionFocusUseCase = mockk(relaxed = true),
    prepareCollectionQueueUseCase = mockk(relaxed = true),
    mediaRepository = mockk(relaxed = true),
    getRelatedMediaUseCase = mockk(relaxed = true),
    resolveMediaPlayTargetUseCase = mockk(relaxed = true),
    mediaPlaybackTracker = mockk(relaxed = true),
    mediaAvailabilityVerifier = mockk(relaxed = true),
    mediaDownloadDelegate = mockk(relaxed = true),
    mediaSeriesDelegate = mockk(relaxed = true),
    mediaSiblingsDelegate = mockk(relaxed = true)
)
